[package]
name = "cyber_range"
version = "0.1.0"
authors = ["takesyhi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.5"
log = "0.4"
env_logger = "0.6.1"
num-traits = "0.2"
num-derive = "0.3"
